title: My Musings
description: An attempt to publish more
url: "https://sandmanextraordinaire.github.io"  # your GitHub Pages URL for now
baseurl: "/singularity"              # the name of your repo, or "" if it's username.github.io

theme: minima

author:
  name: Sandeep
  email: sandeep.kprao@gmail.com
